<?php
/**
 * RefundsApi
 * PHP version 7.4
 *
 * @category Class
 * @package  ChannelEngine\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.19.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChannelEngine\Merchant\ApiClient\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ChannelEngine\Merchant\ApiClient\ApiException;
use ChannelEngine\Merchant\ApiClient\Configuration;
use ChannelEngine\Merchant\ApiClient\HeaderSelector;
use ChannelEngine\Merchant\ApiClient\ObjectSerializer;

/**
 * RefundsApi Class Doc Comment
 *
 * @category Class
 * @package  ChannelEngine\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RefundsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'refundAcknowledge' => [
            'application/json-patch+json',
            'application/json',
            'application/*+json',
        ],
        'refundCreate' => [
            'application/json-patch+json',
            'application/json',
            'application/*+json',
        ],
        'refundGet' => [
            'application/json',
        ],
        'refundGetByFilter' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation refundAcknowledge
     *
     * [CLOSED BETA] Acknowledge a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantAcknowledgeRefundRequest|null $singleMerchantAcknowledgeRefundRequest The refund to acknowledge (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundAcknowledge'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ChannelEngine\Merchant\ApiClient\Model\ApiResponse
     */
    public function refundAcknowledge($singleMerchantAcknowledgeRefundRequest = null, string $contentType = self::contentTypes['refundAcknowledge'][0])
    {
        list($response) = $this->refundAcknowledgeWithHttpInfo($singleMerchantAcknowledgeRefundRequest, $contentType);
        return $response;
    }

    /**
     * Operation refundAcknowledgeWithHttpInfo
     *
     * [CLOSED BETA] Acknowledge a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantAcknowledgeRefundRequest|null $singleMerchantAcknowledgeRefundRequest The refund to acknowledge (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundAcknowledge'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ChannelEngine\Merchant\ApiClient\Model\ApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function refundAcknowledgeWithHttpInfo($singleMerchantAcknowledgeRefundRequest = null, string $contentType = self::contentTypes['refundAcknowledge'][0])
    {
        $request = $this->refundAcknowledgeRequest($singleMerchantAcknowledgeRefundRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation refundAcknowledgeAsync
     *
     * [CLOSED BETA] Acknowledge a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantAcknowledgeRefundRequest|null $singleMerchantAcknowledgeRefundRequest The refund to acknowledge (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundAcknowledge'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundAcknowledgeAsync($singleMerchantAcknowledgeRefundRequest = null, string $contentType = self::contentTypes['refundAcknowledge'][0])
    {
        return $this->refundAcknowledgeAsyncWithHttpInfo($singleMerchantAcknowledgeRefundRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refundAcknowledgeAsyncWithHttpInfo
     *
     * [CLOSED BETA] Acknowledge a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantAcknowledgeRefundRequest|null $singleMerchantAcknowledgeRefundRequest The refund to acknowledge (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundAcknowledge'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundAcknowledgeAsyncWithHttpInfo($singleMerchantAcknowledgeRefundRequest = null, string $contentType = self::contentTypes['refundAcknowledge'][0])
    {
        $returnType = '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse';
        $request = $this->refundAcknowledgeRequest($singleMerchantAcknowledgeRefundRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'refundAcknowledge'
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantAcknowledgeRefundRequest|null $singleMerchantAcknowledgeRefundRequest The refund to acknowledge (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundAcknowledge'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function refundAcknowledgeRequest($singleMerchantAcknowledgeRefundRequest = null, string $contentType = self::contentTypes['refundAcknowledge'][0])
    {



        $resourcePath = '/v2.1/refunds/merchant/acknowledge';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($singleMerchantAcknowledgeRefundRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($singleMerchantAcknowledgeRefundRequest));
            } else {
                $httpBody = $singleMerchantAcknowledgeRefundRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation refundCreate
     *
     * [CLOSED BETA] Create a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantCreateRefundRequest|null $singleMerchantCreateRefundRequest The refund (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundCreate'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ChannelEngine\Merchant\ApiClient\Model\ApiResponse|\ChannelEngine\Merchant\ApiClient\Model\ApiResponse
     */
    public function refundCreate($singleMerchantCreateRefundRequest = null, string $contentType = self::contentTypes['refundCreate'][0])
    {
        list($response) = $this->refundCreateWithHttpInfo($singleMerchantCreateRefundRequest, $contentType);
        return $response;
    }

    /**
     * Operation refundCreateWithHttpInfo
     *
     * [CLOSED BETA] Create a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantCreateRefundRequest|null $singleMerchantCreateRefundRequest The refund (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundCreate'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ChannelEngine\Merchant\ApiClient\Model\ApiResponse|\ChannelEngine\Merchant\ApiClient\Model\ApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function refundCreateWithHttpInfo($singleMerchantCreateRefundRequest = null, string $contentType = self::contentTypes['refundCreate'][0])
    {
        $request = $this->refundCreateRequest($singleMerchantCreateRefundRequest, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 201:
                    if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation refundCreateAsync
     *
     * [CLOSED BETA] Create a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantCreateRefundRequest|null $singleMerchantCreateRefundRequest The refund (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundCreateAsync($singleMerchantCreateRefundRequest = null, string $contentType = self::contentTypes['refundCreate'][0])
    {
        return $this->refundCreateAsyncWithHttpInfo($singleMerchantCreateRefundRequest, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refundCreateAsyncWithHttpInfo
     *
     * [CLOSED BETA] Create a refund
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantCreateRefundRequest|null $singleMerchantCreateRefundRequest The refund (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundCreateAsyncWithHttpInfo($singleMerchantCreateRefundRequest = null, string $contentType = self::contentTypes['refundCreate'][0])
    {
        $returnType = '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse';
        $request = $this->refundCreateRequest($singleMerchantCreateRefundRequest, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'refundCreate'
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\SingleMerchantCreateRefundRequest|null $singleMerchantCreateRefundRequest The refund (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundCreate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function refundCreateRequest($singleMerchantCreateRefundRequest = null, string $contentType = self::contentTypes['refundCreate'][0])
    {



        $resourcePath = '/v2.1/refunds/merchant';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($singleMerchantCreateRefundRequest)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($singleMerchantCreateRefundRequest));
            } else {
                $httpBody = $singleMerchantCreateRefundRequest;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation refundGet
     *
     * [CLOSED BETA] Get refund by identifier
     *
     * @param  string $identifier The identifier to search for (required)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundIdentifier|null $type Specify whether to search by ID, Merchant Refund No or Channel Refund No (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGet'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund|\ChannelEngine\Merchant\ApiClient\Model\ApiResponse
     */
    public function refundGet($identifier, $type = null, string $contentType = self::contentTypes['refundGet'][0])
    {
        list($response) = $this->refundGetWithHttpInfo($identifier, $type, $contentType);
        return $response;
    }

    /**
     * Operation refundGetWithHttpInfo
     *
     * [CLOSED BETA] Get refund by identifier
     *
     * @param  string $identifier The identifier to search for (required)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundIdentifier|null $type Specify whether to search by ID, Merchant Refund No or Channel Refund No (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGet'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund|\ChannelEngine\Merchant\ApiClient\Model\ApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function refundGetWithHttpInfo($identifier, $type = null, string $contentType = self::contentTypes['refundGet'][0])
    {
        $request = $this->refundGetRequest($identifier, $type, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation refundGetAsync
     *
     * [CLOSED BETA] Get refund by identifier
     *
     * @param  string $identifier The identifier to search for (required)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundIdentifier|null $type Specify whether to search by ID, Merchant Refund No or Channel Refund No (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundGetAsync($identifier, $type = null, string $contentType = self::contentTypes['refundGet'][0])
    {
        return $this->refundGetAsyncWithHttpInfo($identifier, $type, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refundGetAsyncWithHttpInfo
     *
     * [CLOSED BETA] Get refund by identifier
     *
     * @param  string $identifier The identifier to search for (required)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundIdentifier|null $type Specify whether to search by ID, Merchant Refund No or Channel Refund No (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundGetAsyncWithHttpInfo($identifier, $type = null, string $contentType = self::contentTypes['refundGet'][0])
    {
        $returnType = '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund';
        $request = $this->refundGetRequest($identifier, $type, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'refundGet'
     *
     * @param  string $identifier The identifier to search for (required)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundIdentifier|null $type Specify whether to search by ID, Merchant Refund No or Channel Refund No (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGet'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function refundGetRequest($identifier, $type = null, string $contentType = self::contentTypes['refundGet'][0])
    {

        // verify the required parameter 'identifier' is set
        if ($identifier === null || (is_array($identifier) && count($identifier) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $identifier when calling refundGet'
            );
        }



        $resourcePath = '/v2.1/refunds/merchant/{identifier}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $type,
            'type', // param base name
            'RefundIdentifier', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($identifier !== null) {
            $resourcePath = str_replace(
                '{' . 'identifier' . '}',
                ObjectSerializer::toPathValue($identifier),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation refundGetByFilter
     *
     * [CLOSED BETA] Get refunds by filter
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundByFilterIdentifier|null $identifiersIdentifierType The type of identifier: which identifier to filter on (optional)
     * @param  string[]|null $identifiersModels The value (of the selected type) to filter on (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleChannelExportStatus[]|null $channelExportStatusStatuses channelExportStatusStatuses (optional)
     * @param  int|null $channelExportStatusMaxNumberOfExportAttempts channelExportStatusMaxNumberOfExportAttempts (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundReason[]|null $reasons reasons (optional)
     * @param  \DateTime|null $createdDateRangeFromDate createdDateRangeFromDate (optional)
     * @param  \DateTime|null $createdDateRangeToDate createdDateRangeToDate (optional)
     * @param  int[]|null $channelIds channelIds (optional)
     * @param  string|null $search search (optional)
     * @param  bool|null $isAcknowledgedByMerchant isAcknowledgedByMerchant (optional)
     * @param  bool|null $isAcknowledgedByChannel isAcknowledgedByChannel (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleFulfillmentType|null $fulfillmentType fulfillmentType (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\CreatorType|null $creatorType creatorType (optional)
     * @param  string[]|null $externalBatchNos externalBatchNos (optional)
     * @param  int|null $page Page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGetByFilter'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund|\ChannelEngine\Merchant\ApiClient\Model\ApiResponse
     */
    public function refundGetByFilter($identifiersIdentifierType = null, $identifiersModels = null, $channelExportStatusStatuses = null, $channelExportStatusMaxNumberOfExportAttempts = null, $reasons = null, $createdDateRangeFromDate = null, $createdDateRangeToDate = null, $channelIds = null, $search = null, $isAcknowledgedByMerchant = null, $isAcknowledgedByChannel = null, $fulfillmentType = null, $creatorType = null, $externalBatchNos = null, $page = null, string $contentType = self::contentTypes['refundGetByFilter'][0])
    {
        list($response) = $this->refundGetByFilterWithHttpInfo($identifiersIdentifierType, $identifiersModels, $channelExportStatusStatuses, $channelExportStatusMaxNumberOfExportAttempts, $reasons, $createdDateRangeFromDate, $createdDateRangeToDate, $channelIds, $search, $isAcknowledgedByMerchant, $isAcknowledgedByChannel, $fulfillmentType, $creatorType, $externalBatchNos, $page, $contentType);
        return $response;
    }

    /**
     * Operation refundGetByFilterWithHttpInfo
     *
     * [CLOSED BETA] Get refunds by filter
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundByFilterIdentifier|null $identifiersIdentifierType The type of identifier: which identifier to filter on (optional)
     * @param  string[]|null $identifiersModels The value (of the selected type) to filter on (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleChannelExportStatus[]|null $channelExportStatusStatuses (optional)
     * @param  int|null $channelExportStatusMaxNumberOfExportAttempts (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundReason[]|null $reasons (optional)
     * @param  \DateTime|null $createdDateRangeFromDate (optional)
     * @param  \DateTime|null $createdDateRangeToDate (optional)
     * @param  int[]|null $channelIds (optional)
     * @param  string|null $search (optional)
     * @param  bool|null $isAcknowledgedByMerchant (optional)
     * @param  bool|null $isAcknowledgedByChannel (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleFulfillmentType|null $fulfillmentType (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\CreatorType|null $creatorType (optional)
     * @param  string[]|null $externalBatchNos (optional)
     * @param  int|null $page Page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGetByFilter'] to see the possible values for this operation
     *
     * @throws \ChannelEngine\Merchant\ApiClient\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund|\ChannelEngine\Merchant\ApiClient\Model\ApiResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function refundGetByFilterWithHttpInfo($identifiersIdentifierType = null, $identifiersModels = null, $channelExportStatusStatuses = null, $channelExportStatusMaxNumberOfExportAttempts = null, $reasons = null, $createdDateRangeFromDate = null, $createdDateRangeToDate = null, $channelIds = null, $search = null, $isAcknowledgedByMerchant = null, $isAcknowledgedByChannel = null, $fulfillmentType = null, $creatorType = null, $externalBatchNos = null, $page = null, string $contentType = self::contentTypes['refundGetByFilter'][0])
    {
        $request = $this->refundGetByFilterRequest($identifiersIdentifierType, $identifiersModels, $channelExportStatusStatuses, $channelExportStatusMaxNumberOfExportAttempts, $reasons, $createdDateRangeFromDate, $createdDateRangeToDate, $channelIds, $search, $isAcknowledgedByMerchant, $isAcknowledgedByChannel, $fulfillmentType, $creatorType, $externalBatchNos, $page, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();


            switch($statusCode) {
                case 200:
                    if ('\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 400:
                    if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ChannelEngine\Merchant\ApiClient\Model\ApiResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw new ApiException(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $request->getUri()
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw new ApiException(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $request->getUri()
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 400:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChannelEngine\Merchant\ApiClient\Model\ApiResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation refundGetByFilterAsync
     *
     * [CLOSED BETA] Get refunds by filter
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundByFilterIdentifier|null $identifiersIdentifierType The type of identifier: which identifier to filter on (optional)
     * @param  string[]|null $identifiersModels The value (of the selected type) to filter on (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleChannelExportStatus[]|null $channelExportStatusStatuses (optional)
     * @param  int|null $channelExportStatusMaxNumberOfExportAttempts (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundReason[]|null $reasons (optional)
     * @param  \DateTime|null $createdDateRangeFromDate (optional)
     * @param  \DateTime|null $createdDateRangeToDate (optional)
     * @param  int[]|null $channelIds (optional)
     * @param  string|null $search (optional)
     * @param  bool|null $isAcknowledgedByMerchant (optional)
     * @param  bool|null $isAcknowledgedByChannel (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleFulfillmentType|null $fulfillmentType (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\CreatorType|null $creatorType (optional)
     * @param  string[]|null $externalBatchNos (optional)
     * @param  int|null $page Page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGetByFilter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundGetByFilterAsync($identifiersIdentifierType = null, $identifiersModels = null, $channelExportStatusStatuses = null, $channelExportStatusMaxNumberOfExportAttempts = null, $reasons = null, $createdDateRangeFromDate = null, $createdDateRangeToDate = null, $channelIds = null, $search = null, $isAcknowledgedByMerchant = null, $isAcknowledgedByChannel = null, $fulfillmentType = null, $creatorType = null, $externalBatchNos = null, $page = null, string $contentType = self::contentTypes['refundGetByFilter'][0])
    {
        return $this->refundGetByFilterAsyncWithHttpInfo($identifiersIdentifierType, $identifiersModels, $channelExportStatusStatuses, $channelExportStatusMaxNumberOfExportAttempts, $reasons, $createdDateRangeFromDate, $createdDateRangeToDate, $channelIds, $search, $isAcknowledgedByMerchant, $isAcknowledgedByChannel, $fulfillmentType, $creatorType, $externalBatchNos, $page, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation refundGetByFilterAsyncWithHttpInfo
     *
     * [CLOSED BETA] Get refunds by filter
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundByFilterIdentifier|null $identifiersIdentifierType The type of identifier: which identifier to filter on (optional)
     * @param  string[]|null $identifiersModels The value (of the selected type) to filter on (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleChannelExportStatus[]|null $channelExportStatusStatuses (optional)
     * @param  int|null $channelExportStatusMaxNumberOfExportAttempts (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundReason[]|null $reasons (optional)
     * @param  \DateTime|null $createdDateRangeFromDate (optional)
     * @param  \DateTime|null $createdDateRangeToDate (optional)
     * @param  int[]|null $channelIds (optional)
     * @param  string|null $search (optional)
     * @param  bool|null $isAcknowledgedByMerchant (optional)
     * @param  bool|null $isAcknowledgedByChannel (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleFulfillmentType|null $fulfillmentType (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\CreatorType|null $creatorType (optional)
     * @param  string[]|null $externalBatchNos (optional)
     * @param  int|null $page Page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGetByFilter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function refundGetByFilterAsyncWithHttpInfo($identifiersIdentifierType = null, $identifiersModels = null, $channelExportStatusStatuses = null, $channelExportStatusMaxNumberOfExportAttempts = null, $reasons = null, $createdDateRangeFromDate = null, $createdDateRangeToDate = null, $channelIds = null, $search = null, $isAcknowledgedByMerchant = null, $isAcknowledgedByChannel = null, $fulfillmentType = null, $creatorType = null, $externalBatchNos = null, $page = null, string $contentType = self::contentTypes['refundGetByFilter'][0])
    {
        $returnType = '\ChannelEngine\Merchant\ApiClient\Model\SingleOfIRefund';
        $request = $this->refundGetByFilterRequest($identifiersIdentifierType, $identifiersModels, $channelExportStatusStatuses, $channelExportStatusMaxNumberOfExportAttempts, $reasons, $createdDateRangeFromDate, $createdDateRangeToDate, $channelIds, $search, $isAcknowledgedByMerchant, $isAcknowledgedByChannel, $fulfillmentType, $creatorType, $externalBatchNos, $page, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'refundGetByFilter'
     *
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundByFilterIdentifier|null $identifiersIdentifierType The type of identifier: which identifier to filter on (optional)
     * @param  string[]|null $identifiersModels The value (of the selected type) to filter on (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleChannelExportStatus[]|null $channelExportStatusStatuses (optional)
     * @param  int|null $channelExportStatusMaxNumberOfExportAttempts (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\RefundReason[]|null $reasons (optional)
     * @param  \DateTime|null $createdDateRangeFromDate (optional)
     * @param  \DateTime|null $createdDateRangeToDate (optional)
     * @param  int[]|null $channelIds (optional)
     * @param  string|null $search (optional)
     * @param  bool|null $isAcknowledgedByMerchant (optional)
     * @param  bool|null $isAcknowledgedByChannel (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\ModuleFulfillmentType|null $fulfillmentType (optional)
     * @param  \ChannelEngine\Merchant\ApiClient\Model\CreatorType|null $creatorType (optional)
     * @param  string[]|null $externalBatchNos (optional)
     * @param  int|null $page Page number (optional)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['refundGetByFilter'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function refundGetByFilterRequest($identifiersIdentifierType = null, $identifiersModels = null, $channelExportStatusStatuses = null, $channelExportStatusMaxNumberOfExportAttempts = null, $reasons = null, $createdDateRangeFromDate = null, $createdDateRangeToDate = null, $channelIds = null, $search = null, $isAcknowledgedByMerchant = null, $isAcknowledgedByChannel = null, $fulfillmentType = null, $creatorType = null, $externalBatchNos = null, $page = null, string $contentType = self::contentTypes['refundGetByFilter'][0])
    {

















        $resourcePath = '/v2.1/refunds/merchant';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $identifiersIdentifierType,
            'identifiers.identifierType', // param base name
            'RefundByFilterIdentifier', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $identifiersModels,
            'identifiers.models', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channelExportStatusStatuses,
            'channelExportStatus.statuses', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channelExportStatusMaxNumberOfExportAttempts,
            'channelExportStatus.maxNumberOfExportAttempts', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $reasons,
            'reasons', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $createdDateRangeFromDate,
            'createdDateRange.fromDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $createdDateRangeToDate,
            'createdDateRange.toDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $channelIds,
            'channelIds', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $search,
            'search', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $isAcknowledgedByMerchant,
            'isAcknowledgedByMerchant', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $isAcknowledgedByChannel,
            'isAcknowledgedByChannel', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $fulfillmentType,
            'fulfillmentType', // param base name
            'ModuleFulfillmentType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $creatorType,
            'creatorType', // param base name
            'CreatorType', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $externalBatchNos,
            'externalBatchNos', // param base name
            'array', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page,
            'page', // param base name
            'integer', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('apikey');
        if ($apiKey !== null) {
            $queryParams['apikey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
