<?php
/**
 * VolumeUnitOfMeasure
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ChannelEngine\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.19.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChannelEngine\Merchant\ApiClient\Model;
use \ChannelEngine\Merchant\ApiClient\ObjectSerializer;

/**
 * VolumeUnitOfMeasure Class Doc Comment
 *
 * @category Class
 * @package  ChannelEngine\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VolumeUnitOfMeasure
{
    /**
     * Possible values of this enum
     */
    public const CUBIC_FEET = 'CUBIC_FEET';

    public const CUBIC_INCHES = 'CUBIC_INCHES';

    public const CUBIC_METER = 'CUBIC_METER';

    public const CUBIC_YARD = 'CUBIC_YARD';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CUBIC_FEET,
            self::CUBIC_INCHES,
            self::CUBIC_METER,
            self::CUBIC_YARD
        ];
    }
}


