<?php
/**
 * FulfillmentStockApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ChannelEngine\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * ChannelEngine Merchant API
 *
 * ChannelEngine API for merchants
 *
 * The version of the OpenAPI document: 2.17.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.8.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ChannelEngine\Merchant\ApiClient\Test\Api;

use \ChannelEngine\Merchant\ApiClient\Configuration;
use \ChannelEngine\Merchant\ApiClient\ApiException;
use \ChannelEngine\Merchant\ApiClient\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * FulfillmentStockApiTest Class Doc Comment
 *
 * @category Class
 * @package  ChannelEngine\Merchant\ApiClient
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class FulfillmentStockApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for fulfillmentStockGetFulfillementStockWithStockLocations
     *
     * Gets product stock across all warehouses with stock locations.
     *
     */
    public function testFulfillmentStockGetFulfillementStockWithStockLocations()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
